name: EstateAgent
main: n3wton.estate.agent.EstateAgent
version: 1.00
softdepend: [Vault, WorldGuard]

commands:
    ea:
        description: Estate Agent Plugin Commands.
        usage: /<command>
